### ISSUE TITLE
Weather Plugin Crashes on Install

### ISSUE THREAD

**Issue by raginn8** [Steinerd/Loupedeck.WeatherPlugin#5]
**Version**
5.8.1.18056

**Submitting a...**
[X ] Bug report

**Current behavior:**
I go to Add-On Manager -> Install Plugin From File
Firstly I get a message saying install was successful, but then another window pops up saying that the install failed due to it crashing.
![image](https://github.com/steinerd/Loupedeck.WeatherPlugin/assets/16074051/05a7c649-c2a5-43fd-a74e-4427e5a0748b)

**Expected behavior:**
Plugin installs correctly

**Steps to reproduce:**
See process I've used under 'Current Behavior' above

**Other information:**
Based on the file extension, I', curious if this is only supported on version 4 of the Loupedeck software. If so, where is this listed and is there a version for the latest?

**Comment by iDeeLaw** [comment]
Ditto. Happen to find a solution?

**Comment by steinerd** [comment]
Appologies folks. 
I have unplugged my Loupedeck for many months now since it would prepetually run the memory up to the point where my computer would blue-screen (and this was on an entirely 'virgin' setup, no plugins or predefined templates). 

---

I've been removed from it all for awhile, and will try to swing back around with the new versioned libs from the Loupedeck SDK, and see if I can resolve this.

**Comment by yanus** [comment]
Hi, hope it's ok to post this here, but with the latest Loupedeck update breaking things again, I've created a new weather plugin (also based on Danol's [original one](https://github.com/CZDanol/loupedeck-weatherwidget)).
You may check it out here: https://github.com/yanus/LoupedeckWeatherPlugin

**Comment by steinerd** [comment]
Totally OK. If you don't mind I'm going to archive THIS repo, and redirect folks to your repo; I don't even have the device any more to test.
